blank_issues_enabled: false
contact_links:
  - name: "Questions / Discussions"
    url: "https://github.com/matt-riley/elysia-crud-template/discussions"
    about: "Please ask and answer questions here."
